name: Maven build
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Maven
      run: mvn --version
